services:
  cimo_ow_nodejs_cpu:
    container_name: cimo-ow-nodejs-cpu
    env_file:
      - ./env/local.env
    build:
      context: ./
      dockerfile: ./docker/Dockerfile_nodejs
      args:
        _ENV_NAME: ${ENV_NAME}
        _DOMAIN: ${DOMAIN}
        _TIME_ZONE: ${TIME_ZONE}
        _LANG: ${LANG}
        _PATH_ROOT: ${PATH_ROOT}
        _NODEJS_SERVER_PORT: ${NODEJS_SERVER_PORT}
        _NODEJS_SERVER_PORT_RANGE: ${NODEJS_SERVER_PORT_RANGE}
    ports:
      - 127.0.0.1:${NODEJS_SERVER_PORT}:${NODEJS_SERVER_PORT}
      - 127.0.0.1:${NODEJS_SERVER_PORT_RANGE}:${NODEJS_SERVER_PORT_RANGE}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:${PATH_ROOT}
      - ms_cronjob-volume:${PATH_ROOT}certificate/:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket
      - /mnt/wslg:/mnt/wslg
  cimo_ow_python_cpu:
    container_name: cimo-ow-python-cpu
    env_file:
      - ./env/local.env
    build:
      context: ./
      dockerfile: ./docker/Dockerfile_python
      args:
        _ENV_NAME: ${ENV_NAME}
        _DOMAIN: ${DOMAIN}
        _TIME_ZONE: ${TIME_ZONE}
        _LANG: ${LANG}
        _PATH_ROOT: ${PATH_ROOT}
        _PYTHON_JUPYTER_PORT: ${PYTHON_JUPYTER_PORT}
    ports:
      - 127.0.0.1:${PYTHON_JUPYTER_PORT}:${PYTHON_JUPYTER_PORT}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:${PATH_ROOT}
      - ms_cronjob-volume:${PATH_ROOT}certificate/:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket
      - /mnt/wslg:/mnt/wslg
    depends_on:
      - cimo_ow_nodejs_cpu
  cimo_ow_apache:
    container_name: cimo-ow-apache
    env_file:
      - ./env/local.env
    build:
      context: ./
      dockerfile: ./docker/Dockerfile_apache
      args:
        _ENV_NAME: ${ENV_NAME}
        _DOMAIN: ${DOMAIN}
        _TIME_ZONE: ${TIME_ZONE}
        _LANG: ${LANG}
        _PATH_ROOT: ${PATH_ROOT}
        _APACHE_SERVER_PORT: ${APACHE_SERVER_PORT}
    ports:
      - 127.0.0.1:443:${APACHE_SERVER_PORT}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:${PATH_ROOT}
      - ms_cronjob-volume:${PATH_ROOT}certificate/:ro
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - cimo_ow_nodejs_cpu
volumes:
  ms_cronjob-volume:
